language: ruby
sudo: false
rvm:
  - 2.2.6
  - 2.3.3
script:
  - cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:migrate
  - cd ../.. && bundle exec rspec spec
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
addons:
  firefox: 31.0esr
