language: ruby
sudo: false
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
script:
  - bundle exec rake tests
addons:
  chrome: stable
before_install:
  - nvm install --lts
  - gem install bundler:1.17.2
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
env:
  - CHROME_PATH=/usr/bin/google-chrome-stable
deploy:
  provider: rubygems
  api_key:
    secure: PEMMDcT4SKPdv4xMJmIEpndOGePsV3kDOhUL0vEDjTeyxBrn+iBgHKF9itSYbUmOSTuOaiIVleYmuC6GoAmg4KcZIZvfCA61cGCX1ADU5nwh5FjC/tAEs8eShMR3RFG6wyykb4MdFkE2jVpm/W0pyciLgW2HrM6iYzI6X2iMn9E=
  gem: activeadmin_addons
  on:
    tags: true
    repo: platanus/activeadmin_addons
